import {test,expect,type Page} from '@playwright/test';
import fs from 'node:fs';
import crypto from 'node:crypto';
// Explicit opt-in; credentials live outside the repo and traces remain off.
const enabled=Boolean(process.env.PROVIO_AUTH_URL&&process.env.PROVIO_TEST_ACCOUNTS);
test.use({trace:'off',video:'off',actionTimeout:10000});
test('authenticated population → independent review → issuance → retested closure',async({page})=>{
 test.skip(!enabled,'Requires a migrated local Supabase Auth/PostgREST stack and synthetic account file.');
 test.setTimeout(120000);
 const {accounts}=JSON.parse(fs.readFileSync(process.env.PROVIO_TEST_ACCOUNTS!,'utf8'));
 const account=(role:string)=>accounts.find((u:{role:string})=>u.role===role);
 const title=`Payments ${crypto.randomUUID()}`;
 async function login(role:string){
  await page.goto(process.env.PROVIO_AUTH_URL!);
  await expect(page.getByRole('button',{name:'Sign out',exact:true}).or(page.getByLabel('Email',{exact:true}))).toBeVisible();
  if(await page.getByRole('button',{name:'Sign out',exact:true}).isVisible())await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.getByLabel('Email',{exact:true}).fill(account(role).email);
  await page.getByLabel('Password',{exact:true}).fill(account(role).password);
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Audit File',exact:true})).toBeVisible();
  await page.getByText('Create procurement engagement',{exact:true}).click();
  await expect(page.locator('select[name=entity] option')).toHaveCount(2);
 }
 async function selectCase(){await expect(page.getByRole('combobox').first().locator('option').filter({hasText:title})).toHaveCount(1);await page.getByRole('combobox').first().selectOption({label:await page.getByRole('combobox').first().locator('option').filter({hasText:title}).innerText()});}
 async function noError(){await expect(page.getByRole('alert')).toHaveCount(0);}
 await login('preparer');
 await page.locator('select[name=entity]').selectOption({index:1});
 await page.getByLabel('Engagement title').fill(title);
 await page.getByRole('button',{name:'Create',exact:true}).click();
 await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();
 await page.getByLabel('CSV file').setInputFiles('docs/fixtures/procurement.csv');
 await page.getByLabel('Independent control total').fill('19600.00');
 await page.getByRole('button',{name:'Validate and commit population'}).click();
 await expect(page.getByText(/Reconciled: 2 rows/)).toBeVisible();await noError();
 await page.getByLabel(/Attach evidence/).setInputFiles({name:'evidence.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic invoice and verification evidence')});
 await expect(page.getByRole('button',{name:'p1',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'p1',exact:true}).click();
 await expect(page.getByLabel('Supporting evidence').locator('option')).toHaveCount(2);
 await page.getByRole('combobox',{name:'Outcome',exact:true}).selectOption('exception');
 await page.getByLabel('Rationale,').fill('Confirmed duplicated payment against original invoice.');
 await page.getByLabel('Supporting evidence').selectOption({index:1});
 await page.getByRole('button',{name:'Save test result',exact:true}).click();
 await expect(page.getByRole('cell',{name:'exception',exact:true})).toBeVisible();
 for(const key of ['condition','criteria','cause','impact','recommendation'])await page.getByLabel(key,{exact:true}).fill(`Documented ${key} for the confirmed duplicate invoice.`);
 await page.getByRole('button',{name:'Save draft finding'}).click();
 await expect(page.getByRole('heading',{name:'Findings (1)'})).toBeVisible();
 await page.getByRole('button',{name:'p2',exact:true}).click();
 await page.getByLabel('Rationale,').fill('Reversal evidence explains flagged transaction; no additional exception.');
 await page.getByLabel('Supporting evidence').selectOption({index:1});
 await page.getByRole('button',{name:'Save test result',exact:true}).click();
 await expect(page.getByText(/2 tested/)).toBeVisible();
 await page.getByRole('button',{name:'Run pre-flight and submit for review'}).click();
 await expect(page.getByText(/testing · submitted/)).toBeVisible();await noError();
 await login('reviewer');await selectCase();
 await page.getByLabel('Independent review conclusion').fill('Independent evidence review confirms ineffective duplicate prevention.');
 await page.getByRole('combobox',{name:'Decision',exact:true}).selectOption('seal');
 await page.getByRole('button',{name:'Commit review decision'}).click();
 await expect(page.getByText(/conclusion · sealed/)).toBeVisible();
 await login('cia');await selectCase();
 await page.getByRole('button',{name:'Issue immutable template report and linked issues'}).click();
 await expect(page.getByText(/conclusion · issued/)).toBeVisible();
 await page.getByLabel('Action / retest rationale').fill('Implemented a duplicate blocking control and verified configuration.');
 await page.getByRole('combobox',{name:'Evidence',exact:true}).selectOption({index:1});
 await page.getByRole('button',{name:'Commit issue action'}).click();
 await expect(page.getByText(/Status: pending_validation/)).toBeVisible();
 await login('reviewer');await selectCase();
 await page.getByRole('combobox',{name:'Action',exact:true}).selectOption('retest');
 await page.getByRole('combobox',{name:'Retest outcome',exact:true}).selectOption('pass');
 await page.getByLabel('Action / retest rationale').fill('Independently tested new duplicate attempts and observed rejection.');
 await page.getByRole('combobox',{name:'Evidence',exact:true}).selectOption({index:1});
 await page.getByRole('button',{name:'Commit issue action'}).click();
 await expect(page.getByText(/Status: validated/)).toBeVisible();
 await page.getByRole('combobox',{name:'Action',exact:true}).selectOption('close_issue');
 await page.getByRole('button',{name:'Commit issue action'}).click();
 await expect(page.getByText(/Status: closed/)).toBeVisible();await noError();
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.setViewportSize({width:1440,height:900});
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export verified history and evidence'}).click();
 const download=await pending;const bundle=JSON.parse(fs.readFileSync((await download.path())!,'utf8'));
 expect(bundle.events.length).toBeGreaterThan(10);expect(bundle.head.seq).toBe(bundle.events.length);
 for(const e of bundle.events)expect(crypto.createHash('sha256').update(e.committed_text).digest('hex')).toBe(e.hash);
 for(const e of bundle.evidence)expect(crypto.createHash('sha256').update(Buffer.from(e.base64,'base64')).digest('hex')).toBe(e.sha256);
 const frozenReport=JSON.parse(bundle.events.find((e:{committed_text:string})=>JSON.parse(e.committed_text).action==='issue').committed_text).state.report;
 expect(JSON.parse(bundle.events.at(-1).committed_text).state.report).toEqual(frozenReport);
 await login('observer');
 await expect(page.getByRole('combobox').first().locator('option')).toHaveCount(1);
 await page.getByRole('button',{name:'Issues Register',exact:true}).click();
 await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();
 await expect(page.locator('article').filter({has:page.getByRole('heading',{name:title,exact:true})}).getByText(/closed/)).toBeVisible();
});
